=== TiagoSilva9607/DWeb2019/TP2/ProjectRecord.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Project-Record (Cabeçalho,Workteam,Abstract,Deliverables)>

<!ELEMENT Cabeçalho (key_name,title,subtitle,begin_date,end_date,supervisor) >
<!ELEMENT  key_name (#PCDATA) >
<!ELEMENT  title (#PCDATA) >
<!ELEMENT  subtitle (#PCDATA)* >
<!ELEMENT  begin_date (#PCDATA) >
<!ELEMENT  end_date (#PCDATA) >
<!ELEMENT  supervisor (nome+,url+) >
<!ELEMENT  nome (#PCDATA) >
<!ELEMENT  url (#PCDATA) >

<!ELEMENT Workteam ( individuo+,identificador+,git+,email+) >
<!ELEMENT  individuo (#PCDATA) >
<!ELEMENT  identificador (#PCDATA) >
<!ELEMENT  git (#PCDATA) >
<!ELEMENT  email (#PCDATA) >

<!ELEMENT Abstract (#PCDATA|links)* >
<!ELEMENT  links (#PCDATA) >

<!ELEMENT Deliverables (link+) >
<!ELEMENT  link (#PCDATA) >

=== TiagoSilva9607/DWeb2019/TP2/Project-Record.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Project-Record SYSTEM "file:/C:/Users/Tiago/Desktop/Mestrado%20UMinho/4%C2%BAAno/web/TP2/ProjectRecord.dtd">
<Project-Record>
    <Cabeçalho>
        <key_name></key_name>
        <title></title>
        <subtitle></subtitle>
        <begin_date></begin_date>
        <end_date></end_date>
        <supervisor>
            <nome></nome>
        </supervisor>
    </Cabeçalho>
    <Workteam>
        <individuo></individuo>
    </Workteam>
    <Abstract></Abstract>
    <Deliverables>
        <link></link>
    </Deliverables>
</Project-Record>
